const MENSAJES: Record<string, string[]> = {
  'calma-sanando': [
    'Soltar también es una decisión. Y a veces, la más difícil.',
    'No todo necesita ser resuelto. Algunas cosas solo necesitan tiempo.',
    'La calma no es la ausencia de ruido. Es saber que el ruido no te define.',
    'Parar no es perder. A veces es la única forma de avanzar.',
    'Lo que ya no sirve ocupa espacio. Tú decides cuánto.',
    'No tienes que estar bien para seguir. Puedes seguir mientras sanas.',
    'El descanso no es premio. Es parte del proceso.',
    'Algunas cosas no se resuelven. Se superan.',
    'Hoy no tienes que tenerlo todo claro.',
    'Sanar en silencio también cuenta.',
    'No te compares con quien eras antes del golpe. Ese ya no es el punto.',
    'Lo que sueltas hoy deja espacio para algo mejor.',
    'No todo tiene solución. Pero todo tiene fin.',
    'La calma que buscas fuera ya existe dentro. Solo está enterrada.',
    'Tomarte tiempo no es rendirte.',
    'No tienes que justificar tu necesidad de parar.',
    'El cuerpo sabe antes que la mente. Escúchalo.',
    'No hay prisa en sanar. El proceso tiene su propio ritmo.',
    'A veces lo más productivo que puedes hacer es no hacer nada.',
    'No estás atascado. Estás procesando.',
    'Cada día que avanzas un poco, aunque no lo notes, es suficiente.',
    'La resistencia cansa más que el problema.',
    'Perdonar no es olvidar. Es dejar de cargar.',
    'No todo lo que pesa tiene que quedarse.',
    'El equilibrio no se encuentra. Se practica.',
    'Estar tranquilo no significa estar dormido.',
    'La paz no es un destino. Es una elección diaria.',
    'No tienes que resolver todo hoy.',
    'Respirar también es una estrategia.',
    'Lo que ya pasó no necesita más energía tuya.',
    'Sanar no es lineal. Los retrocesos también son parte.',
    'No tienes que demostrar nada mientras te recuperas.',
    'El tiempo que dedicas a cuidarte no es tiempo perdido.',
    'No hay versión correcta de cómo sanar.',
    'Confiar en el proceso también cuando el proceso duele.',
    'No necesitas tener todo bajo control para estar bien.',
    'Algunas heridas necesitan aire, no más vendas.',
    'Lo que te costó llegar hasta aquí también cuenta.',
    'No te exijas más de lo que puedes hoy.',
    'Descansar no te hace menos.',
    'La calma también se construye con pequeñas decisiones.',
    'No tienes que ser fuerte todo el tiempo.',
    'El movimiento hacia adelante no siempre se ve. Pero ocurre.',
    'Hoy con mantenerte es suficiente.',
    'No compares tu proceso con el de nadie.',
    'Cuidarte no es egoísmo. Es mantenimiento.',
    'El descanso intencional es diferente a la parálisis.',
    'No tienes que llegar a ningún lado hoy.',
    'La serenidad no es indiferencia. Es perspectiva.',
    'Permítete no saber cómo estás. A veces eso también pasa.',
    'No todo silencio es vacío. Algunos son necesarios.',
    'Lo que hoy parece enorme, mañana será manejable.',
    'No hay atajos en sanar. Pero sí hay apoyo.',
    'Cada pequeño paso en la dirección correcta suma.',
    'No tienes que entender todo para seguir.',
    'La pausa también es movimiento.',
    'No siempre hay lección en el dolor. A veces solo hay dolor.',
    'Darte permiso para estar mal es el primer paso para estar mejor.',
    'No tienes que tener ganas para empezar.',
    'El orden interno no llega solo. Se trabaja.',
    'No necesitas razones para cuidarte.',
    'Lo que sientes es válido aunque no lo entiendas.',
    'No toda calma es pasividad. Algunas son poder.',
  ],
  'calma-construyendo': [
    'Lo que construyes despacio, dura.',
    'La prisa es cara. La paciencia, rentable.',
    'No todo avance es visible. Sigue.',
    'Construir con calma no es ir lento. Es ir seguro.',
    'El ritmo también es una elección estratégica.',
    'Los mejores proyectos no se apresuran.',
    'La constancia tranquila gana a la intensidad errática.',
    'Un paso al día es 365 pasos al año.',
    'No hace falta correr si vas en la dirección correcta.',
    'La urgencia artificial destruye más de lo que construye.',
    'Lo que haces hoy con intención vale más que lo que haces mañana con prisa.',
    'No necesitas hacerlo todo a la vez.',
    'Construir bien requiere parar y revisar.',
    'La calidad de lo que haces depende de la calidad de tu estado.',
    'No todo lo urgente es importante.',
    'El mejor cimiento es el que no se ve pero aguanta todo.',
    'Construir sin prisa no significa construir sin propósito.',
    'La energía bien dirigida supera a la energía dispersa.',
    'No tienes que demostrar velocidad. Solo resultados.',
    'El proceso también es parte del producto.',
    'Construir en calma es un acto de confianza en ti mismo.',
    'No hay que hacer ruido para avanzar.',
    'Lo que construyes con foco deja huella.',
    'La claridad antes de la acción ahorra mucho después.',
    'No toda pausa es retraso. Algunas son necesarias.',
    'Hacer menos cosas, pero hacerlas bien.',
    'El silencio también es parte de construir.',
    'No midas el progreso solo en velocidad.',
    'La constancia sin prisa es imbatible.',
    'Lo que haces hoy con calma, mañana es base.',
    'Construir con intención es diferente a construir con ansiedad.',
    'No todo lo que se puede hacer hay que hacerlo ahora.',
    'El equilibrio entre avanzar y descansar es también habilidad.',
    'No necesitas más energía. Necesitas mejor dirección.',
    'Cada decisión tranquila es un ladrillo bien puesto.',
    'Lo que construyes en orden resiste más que lo que construyes en caos.',
    'No te midas con quien va más rápido. Mídete con quien va mejor.',
    'La paciencia aplicada es estrategia, no pasividad.',
    'Construir despacio también es respetarte.',
    'No necesitas hacerlo perfecto. Necesitas hacerlo bien.',
    'El foco sostenido construye más que los sprints intermitentes.',
    'No toda acción suma. Elige cuáles importan.',
    'Construir con calma genera menos errores y más solidez.',
    'No hay mérito en el agotamiento. Hay mérito en los resultados.',
    'La tranquilidad mientras construyes también es parte del resultado.',
    'No midas el valor de lo que haces por el esfuerzo que te costó.',
    'Construir bien es también saber cuándo parar.',
    'La claridad de propósito compensa la falta de velocidad.',
    'No tienes que hacer todo a la vez para llegar lejos.',
    'El trabajo bien hecho no necesita ser explicado.',
    'Construir desde la calma atrae lo correcto.',
    'No te compares con tu versión de ayer si hoy tienes más contexto.',
    'La dirección importa más que la velocidad.',
    'No todo lo que brilla rápido dura.',
    'Construir con calma es una ventaja competitiva.',
    'No necesitas presión externa para avanzar si tienes claridad interna.',
    'El trabajo profundo requiere mente tranquila.',
    'No todo hay que resolverlo hoy. Pero sí hay que avanzar.',
    'Construir en silencio y dejar que los resultados hablen.',
    'La calma productiva es una de las habilidades más valiosas.',
    'No todo esfuerzo visible es progreso real.',
    'El ritmo sostenible gana al sprint agotador.',
    'Construir bien hoy es no tener que rehacer mañana.',
  ],
  'calma-buscando': [
    'A veces la respuesta no llega cuando la buscas. Llega cuando paras.',
    'No saber es incómodo. También es honesto.',
    'El camino no siempre se ve entero. Con ver el siguiente paso es suficiente.',
    'Buscar con calma es una ventaja, no una debilidad.',
    'La claridad no se fuerza. Se permite.',
    'No toda búsqueda necesita urgencia.',
    'La tranquilidad mientras buscas también es información.',
    'No tienes que encontrar todo hoy.',
    'Buscar despacio es buscar mejor.',
    'La respuesta correcta raramente llega bajo presión.',
    'No todo camino está señalizado. A veces hay que fiarse del instinto.',
    'Buscar con calma filtra lo que no es para ti.',
    'No necesitas certeza para dar el siguiente paso.',
    'La búsqueda tranquila tiene más claridad que la búsqueda ansiosa.',
    'No todo lo que buscas fuera está fuera.',
    'Parar a escuchar también es buscar.',
    'No tienes que tener todas las respuestas para seguir adelante.',
    'La calma en la búsqueda atrae lo correcto.',
    'No toda incertidumbre es amenaza. Algunas son oportunidad.',
    'Buscar sin prisa permite ver lo que la prisa oculta.',
    'No te exijas encontrar. Permítete explorar.',
    'La pausa en la búsqueda también revela.',
    'No todo silencio es vacío. Algunos son respuestas.',
    'Buscar con intención pero sin ansiedad es el punto medio.',
    'No necesitas el mapa completo para empezar a caminar.',
    'La calma mientras buscas también es confianza en ti.',
    'No toda pregunta necesita respuesta inmediata.',
    'Buscar desde la calma es buscar desde la fortaleza.',
    'No te pierdas en el camino intentando encontrar el destino.',
    'La dirección importa más que la certeza.',
    'No tienes que saber todo para decidir bien.',
    'Buscar con calma no es conformarse. Es ser estratégico.',
    'No toda búsqueda tiene fin claro. Y está bien.',
    'La tranquilidad en la incertidumbre es madurez.',
    'No necesitas apurarte para encontrar lo correcto.',
    'Buscar bien requiere también saber parar.',
    'No todo lo que no encuentras hoy está perdido.',
    'La calma es la mejor herramienta de búsqueda.',
    'No tienes que resolver la incertidumbre. Solo convivir con ella.',
    'Buscar desde la calma genera mejores preguntas.',
    'No toda respuesta llega cuando se pide.',
    'La búsqueda consciente es más efectiva que la búsqueda desesperada.',
    'No te angusties por no encontrar. Confía en el proceso.',
    'Buscar con paciencia es también una forma de respetarte.',
    'No todo lo que buscas llega en el momento que quieres.',
    'La calma en la búsqueda también atrae claridad.',
    'No tienes que forzar ninguna respuesta.',
    'Buscar tranquilo permite ver lo que la ansiedad ciega.',
    'No toda duda es señal de estar perdido.',
    'La búsqueda sin prisa llega más lejos.',
    'No necesitas certeza total para tomar la siguiente decisión.',
    'Buscar desde la calma es buscar desde el poder.',
    'No toda búsqueda es lineal. Los rodeos también enseñan.',
    'La tranquilidad mientras buscas es también una respuesta.',
    'No tienes que encontrarlo todo solo.',
    'Buscar con calma es también confiar en ti.',
    'No toda incertidumbre dura. La mayoría se resuelve sola.',
    'La búsqueda paciente encuentra lo que la urgente pierde.',
    'No te midas por lo rápido que encuentras. Mídete por lo que encuentras.',
    'Buscar bien es también saber qué no buscar.',
    'No toda pausa en la búsqueda es retroceso.',
    'La calma no frena la búsqueda. La mejora.',
  ],
  'calma-disfrutando': [
    'Esto que tienes ahora es suficiente. ¿Lo estás viendo?',
    'Disfrutar también requiere atención.',
    'No todo tiene que ir a algún lado. Algunas cosas solo tienen que ser.',
    'Estar bien no necesita justificación.',
    'La gratitud silenciosa es la más real.',
    'No tienes que ganarte el descanso.',
    'Disfrutar el presente no es conformismo. Es inteligencia.',
    'No toda felicidad es ruidosa. Las mejores suelen ser silenciosas.',
    'Lo que tienes hoy costó llegar. Reconócelo.',
    'No necesitas más para estar bien si ya estás bien.',
    'Disfrutar sin culpa también es una habilidad.',
    'No todo momento tiene que ser productivo.',
    'La calma del que tiene suficiente es una de las mejores sensaciones.',
    'No tienes que justificar por qué estás bien.',
    'Disfrutar de lo que hay es también una forma de agradecer.',
    'No toda paz es aburrimiento. Algunas son logro.',
    'Lo ordinario bien vivido es extraordinario.',
    'No necesitas más cuando sabes apreciar lo que tienes.',
    'Disfrutar consciente es diferente a disfrutar por inercia.',
    'No todo tiene que cambiar para estar bien.',
    'La calma del que disfruta es contagiosa.',
    'No tienes que buscar más si ya encontraste algo bueno.',
    'Disfrutar el proceso también es parte del resultado.',
    'No toda satisfacción viene del logro. Algunas vienen del ser.',
    'Lo que tienes vale más de lo que crees.',
    'No necesitas compararte para saber que estás bien.',
    'Disfrutar sin prisa es un arte.',
    'No todo tiene que mejorarse. Algunas cosas solo tienen que vivirse.',
    'La gratitud activa lo que la queja bloquea.',
    'No tienes que esperar a algo grande para estar bien.',
    'Disfrutar lo pequeño es sabiduría, no conformismo.',
    'No toda calma es pasividad. Algunas son plenitud.',
    'Lo cotidiano bien vivido es lo que más recordarás.',
    'No necesitas validación para disfrutar de lo que tienes.',
    'Disfrutar es también una elección.',
    'No todo tiene que tener propósito para tener valor.',
    'La paz que sientes hoy es el resultado de decisiones pasadas.',
    'No tienes que merecerte el bienestar. Ya lo tienes.',
    'Disfrutar sin culpa es madurez emocional.',
    'No toda quietud es vacío. Algunas son plenitud.',
    'Lo que disfrutas hoy es también lo que te da energía para mañana.',
    'No necesitas más ruido para saber que estás vivo.',
    'Disfrutar de lo que hay es también estrategia.',
    'No todo lo bueno está en el futuro.',
    'La calma que sientes hoy es también un logro.',
    'No tienes que pedir permiso para estar bien.',
    'Disfrutar consciente multiplica la experiencia.',
    'No todo momento tranquilo hay que llenarlo.',
    'Lo que ya tienes también merece tu atención.',
    'No necesitas más para empezar a disfrutar. Puedes empezar ahora.',
    'Disfrutar el presente no cierra el futuro. Lo alimenta.',
    'No toda satisfacción viene de lograr más.',
    'La calma sostenida es un indicador de que algo estás haciendo bien.',
    'No tienes que irte a ningún lado para estar bien. Ya estás.',
    'Disfrutar también es productivo.',
    'No todo bienestar necesita ser grande para ser real.',
    'La paz cotidiana vale más que los picos de felicidad.',
    'No necesitas más para estar agradecido. Ya tienes suficiente.',
    'Disfrutar sin prisa es también una forma de vivir mejor.',
    'No toda calma es temporal. Puedes quedarte aquí.',
    'Lo que disfrutas hoy también te define.',
    'No tienes que esperar a merecer el descanso. Ya lo mereces.',
  ],
  'crecimiento-construyendo': [
    'Cada decisión que tomas hoy es arquitectura de lo que serás.',
    'No esperes tener todo claro para empezar. La claridad viene con el movimiento.',
    'Lo que construyes importa. Aunque todavía no se vea.',
    'El crecimiento real no se anuncia. Se nota.',
    'Estás más avanzado de lo que crees. No pares.',
    'Construir y crecer al mismo tiempo es posible. Es lo más humano.',
    'No hay versión final de ti. Siempre hay siguiente nivel.',
    'Lo que hoy te cuesta mañana te define.',
    'No tienes que estar listo para empezar. Empezar es lo que te prepara.',
    'Cada error en lo que construyes es un dato, no un fracaso.',
    'Lo que construyes con propósito tiene más durabilidad.',
    'No te quedes en la planificación eterna. En algún punto hay que hacer.',
    'El crecimiento sin acción es solo teoría.',
    'No tienes que saber todo el camino. Solo el siguiente paso.',
    'Construir algo real requiere tolerar la incomodidad.',
    'No todo lo que construyes tiene que ser perfecto para ser válido.',
    'El progreso visible es lento. El invisible, constante.',
    'No necesitas permiso para construir lo que imaginas.',
    'Cada versión de lo que construyes es mejor que la anterior si aprendes.',
    'No te compares con quien ya llegó. Compárate con quien eras.',
    'Construir requiere también saber qué no construir.',
    'No toda acción construye. Elige bien cuáles haces.',
    'El crecimiento real incomoda antes de liberar.',
    'No tienes que construirlo solo. Pero sí tienes que liderarlo.',
    'Lo que construyes con consistencia supera a lo que construyes con intensidad.',
    'No todo lo que derrumba destruye. Algunas cosas se derrumban para mejorar.',
    'El crecimiento también requiere soltar versiones anteriores de ti.',
    'No tienes que tener todo bajo control para avanzar.',
    'Construir bien hoy es no tener que rehacer mañana.',
    'No toda crítica frena. Algunas aceleran.',
    'El crecimiento sin dirección es solo movimiento.',
    'No tienes que esperar a estar listo. Listo es un estado que nunca llega del todo.',
    'Construir algo nuevo siempre empieza con una decisión incómoda.',
    'No todo lo que ves construir a otros es lo que tú necesitas construir.',
    'El crecimiento real deja evidencia. Búscala.',
    'No tienes que tener el plan completo. Tienes que tener el siguiente paso.',
    'Construir requiere también saber cuándo parar y revisar.',
    'No todo esfuerzo produce crecimiento. El esfuerzo dirigido, sí.',
    'El crecimiento sostenido requiere hábitos más que motivación.',
    'No te midas por lo que aún no tienes. Mídete por lo que ya has construido.',
    'Construir algo que dure requiere paciencia estratégica.',
    'No toda incomodidad es señal de ir mal. A veces es señal de crecer.',
    'El crecimiento también requiere gestionar el miedo, no eliminarlo.',
    'No tienes que construir rápido. Tienes que construir bien.',
    'Cada vez que superas algo, tu techo sube.',
    'No toda resistencia es obstáculo. Algunas son entrenamiento.',
    'El crecimiento real no depende de las circunstancias.',
    'No tienes que hacer todo perfecto para crecer. Solo tienes que hacer.',
    'Construir con propósito claro es construir con ventaja.',
    'No todo lo que construyes tiene que gustar a todos.',
    'El crecimiento no espera al momento perfecto.',
    'No tienes que tener más recursos para empezar. Empieza con lo que tienes.',
    'Construir algo propio, aunque sea pequeño, tiene un valor único.',
    'No toda velocidad es progreso. A veces ir más lento es ir mejor.',
    'El crecimiento también se mide en lo que ya no te afecta.',
    'No tienes que construir lo mismo que los demás para llegar lejos.',
    'Cada día que construyes algo es un día que no desperdiciaste.',
    'No todo lo que construyes saldrá como planeaste. Eso también es información.',
    'El crecimiento requiere también honestidad sobre dónde estás.',
    'No tienes que llegar lejos de golpe. Solo tienes que no parar.',
    'Construir desde la claridad es más efectivo que construir desde la urgencia.',
    'No todo lo que construyes hoy lo verás mañana. Pero lo verás.',
  ],
  'crecimiento-sanando': [
    'Sanar no es volver a ser quien eras. Es convertirte en quien puedes ser.',
    'Lo que viviste también te enseñó algo. ¿Ya sabes qué?',
    'El crecimiento a veces duele. Eso no lo hace menos válido.',
    'No tienes que estar bien para avanzar. Puedes avanzar mientras sanas.',
    'Las grietas también son mapa. Muestran por dónde has pasado.',
    'Sanar y crecer no son caminos distintos. Son el mismo.',
    'No tienes que olvidar para seguir.',
    'Lo que superaste ya cambió quién eres.',
    'No hay crecimiento sin algún tipo de pérdida previa.',
    'Sanar también requiere decisión, no solo tiempo.',
    'No tienes que entender todo lo que viviste para crecer con ello.',
    'Lo que rompiste también te mostró de qué estás hecho.',
    'No todo dolor es en vano. Algunos construyen.',
    'Sanar con intención es diferente a sanar por inercia.',
    'No tienes que haber llegado a fondo para empezar a subir.',
    'Lo que hoy pesa, mañana puede ser fortaleza.',
    'No todo lo que perdiste era tuyo para quedarse.',
    'Sanar también es aprender a no repetir.',
    'No tienes que ser el mismo de antes. Puedes ser mejor.',
    'Lo que te costó también te dio perspectiva.',
    'No todo retroceso es fracaso. Algunos son reorganización.',
    'Sanar sin prisa es sanar de verdad.',
    'No tienes que demostrar nada mientras te reconstruyes.',
    'Lo que viviste no te define. Lo que haces con ello, sí.',
    'No todo lo que duele hay que evitarlo. Algunos dolores son necesarios.',
    'Sanar también es elegir qué llevar contigo y qué dejar.',
    'No tienes que ser fuerte todo el tiempo para crecer.',
    'Lo que aprendiste en los momentos difíciles no tiene precio.',
    'No todo crecimiento viene de los éxitos.',
    'Sanar también es reconocer el punto de partida sin juzgarlo.',
    'No tienes que tener todo resuelto para avanzar.',
    'Lo que superaste ya es parte de tu ventaja.',
    'No todo lo que te rompió te destruyó.',
    'Sanar con propósito es convertir la experiencia en recurso.',
    'No tienes que entender el porqué para seguir.',
    'Lo que no te mató ya lo procesaste. O lo estás procesando.',
    'No todo crecimiento es visible desde dentro.',
    'Sanar también requiere paciencia con uno mismo.',
    'No tienes que justificar tu proceso de recuperación.',
    'Lo que hoy parece cicatriz, mañana puede ser distintivo.',
    'No todo lo que perdiste era necesario para lo que viene.',
    'Sanar también es recuperar la confianza en ti.',
    'No tienes que volver a ser quien eras. Puedes ser más.',
    'Lo que viviste también amplió tu capacidad de entender a otros.',
    'No todo dolor necesita explicación para ser válido.',
    'Sanar es también redefinir qué significa estar bien.',
    'No tienes que haber superado todo para crecer.',
    'Lo que te costó llegar hasta aquí también es mérito.',
    'No todo crecimiento viene acompañado de celebración.',
    'Sanar también es soltar la versión de ti que ya no necesitas.',
    'No tienes que esperar a estar completamente bien para empezar a crecer.',
    'Lo que aprendiste sobre ti en los momentos difíciles vale mucho.',
    'No todo lo que se rompe queda roto para siempre.',
    'Sanar también es aprender a pedirte menos perfección.',
    'No tienes que tener todo bajo control para estar creciendo.',
    'Lo que hoy sientes como limitación mañana puede ser profundidad.',
    'No todo proceso de sanación es igual. El tuyo es tuyo.',
    'Sanar también requiere creer que hay algo al otro lado.',
    'No tienes que saber adónde vas para saber que estás avanzando.',
    'Lo que superaste cambió permanentemente quién eres.',
    'No todo crecimiento llega en los momentos que eliges.',
    'Sanar también es aprender que mereces estar bien.',
  ],
  'crecimiento-buscando': [
    'Buscar ya es moverse. Y moverse ya es crecer.',
    'La incomodidad de no saber es donde empieza todo lo bueno.',
    'No necesitas el destino para empezar. Necesitas dirección.',
    'Cada pregunta que te haces te acerca más a quien realmente eres.',
    'La duda no es el problema. La parálisis sí.',
    'Buscar con intención es ya crecer.',
    'No toda búsqueda termina donde esperabas. A veces termina mejor.',
    'El que busca ya tiene algo que muchos no tienen: movimiento.',
    'No tienes que encontrar todo para crecer. A veces basta con buscar bien.',
    'La búsqueda también te define.',
    'No toda incertidumbre es amenaza. Algunas son el inicio de algo grande.',
    'Buscar con honestidad es más valioso que encontrar con trampa.',
    'No tienes que saber exactamente qué buscas para avanzar.',
    'La búsqueda activa genera oportunidades que la pasividad no ve.',
    'No todo lo que no encuentras hoy está perdido.',
    'Buscar también es una forma de comprometerte contigo.',
    'No toda búsqueda necesita testigos.',
    'La dirección importa más que la certeza sobre el destino.',
    'No tienes que estar seguro para buscar.',
    'Buscar bien requiere también saber qué no merece tu búsqueda.',
    'No toda pregunta sin respuesta es un fracaso.',
    'La búsqueda honesta siempre revela algo útil.',
    'No tienes que tener todo claro para empezar a explorar.',
    'Buscar activamente es diferente a esperar pasivamente.',
    'No toda búsqueda es lineal. Los rodeos también enseñan.',
    'La pregunta correcta vale más que la respuesta equivocada.',
    'No tienes que saber adónde vas para saber que estás en movimiento.',
    'Buscar también requiere tolerar la incertidumbre.',
    'No toda exploración termina en hallazgo. Pero siempre termina en aprendizaje.',
    'La búsqueda con propósito filtra lo que no sirve.',
    'No tienes que encontrar hoy lo que buscas desde hace tiempo.',
    'Buscar desde la honestidad es buscar desde la fortaleza.',
    'No toda búsqueda necesita ser grande para ser valiosa.',
    'La curiosidad activa es uno de los recursos más poderosos.',
    'No tienes que tener el mapa completo para explorar.',
    'Buscar también es una declaración de que crees que hay algo mejor.',
    'No toda duda te paraliza. Algunas te mueven.',
    'La búsqueda consciente genera crecimiento aunque no encuentres lo que buscas.',
    'No tienes que saber exactamente qué quieres para saber qué no quieres.',
    'Buscar con intención es también respetarte.',
    'No toda búsqueda tiene respuesta. Pero todas tienen valor.',
    'La exploración sin miedo es una ventaja enorme.',
    'No tienes que estar perdido para buscar algo mejor.',
    'Buscar también es confiar en que hay algo que encontrar.',
    'No toda incertidumbre necesita resolverse rápido.',
    'La búsqueda también te entrena para cuando encuentres.',
    'No tienes que saber todo para dar el siguiente paso en la búsqueda.',
    'Buscar activamente es diferente a estar insatisfecho.',
    'No toda búsqueda exterior es realmente exterior.',
    'La exploración también requiere soltar lo que ya no sirve.',
    'No tienes que encontrar para haber buscado bien.',
    'Buscar con determinación es ya una forma de crecer.',
    'No toda búsqueda necesita audiencia.',
    'La incertidumbre de buscar es mejor que la certeza de no intentarlo.',
    'No tienes que justificar por qué sigues buscando.',
    'Buscar también te da información sobre ti.',
    'No toda búsqueda termina en respuesta. Algunas terminan en claridad.',
    'La búsqueda sin miedo abre puertas que el miedo mantiene cerradas.',
    'No tienes que tener todo resuelto para seguir explorando.',
    'Buscar bien es también saber cuándo parar y evaluar.',
    'No toda búsqueda es sobre encontrar. Algunas son sobre descartarse.',
    'La exploración activa genera más oportunidades que la espera pasiva.',
  ],
  'crecimiento-disfrutando': [
    'Celebrar lo que ya tienes no frena el crecimiento. Lo alimenta.',
    'El progreso también se mide en lo que ya no te cuesta.',
    'Has llegado hasta aquí. Eso merece un segundo de reconocimiento.',
    'Crecer no siempre es ir a más. A veces es quedarse con lo esencial.',
    'El mejor punto de partida es saber dónde estás y que está bien.',
    'Disfrutar del camino no es conformismo. Es inteligencia.',
    'No todo crecimiento futuro requiere sacrificar el presente.',
    'Lo que ya lograste también es parte de quien eres.',
    'No tienes que esperar a llegar para disfrutar el avance.',
    'Celebrar los logros pequeños también es estrategia.',
    'No toda satisfacción tiene que esperar a lo grande.',
    'Disfrutar lo que ya eres también es crecer.',
    'No tienes que estar insatisfecho para seguir creciendo.',
    'Lo que disfrutas hoy también te da energía para mañana.',
    'No toda ambición requiere tensión constante.',
    'Disfrutar el proceso también forma parte del resultado.',
    'No tienes que estar siempre en modo construcción.',
    'Lo que has conseguido también merece ser celebrado, no solo superado.',
    'No toda pausa en el crecimiento es retroceso. Algunas son consolidación.',
    'Disfrutar de lo que has construido no te hace menos ambicioso.',
    'No tienes que compararte con tu versión futura para valorar la actual.',
    'Lo que ya eres es también un logro.',
    'No toda alegría tiene que venir del siguiente paso.',
    'Disfrutar consciente del presente también alimenta el futuro.',
    'No tienes que posponer la satisfacción siempre.',
    'Lo que tienes hoy fue lo que querías antes.',
    'No toda ambición requiere sacrificar el disfrute.',
    'Disfrutar también es reconocer el esfuerzo que costó llegar.',
    'No tienes que estar siempre buscando más para ser alguien que crece.',
    'Lo que ya conseguiste también define quién eres.',
    'No toda satisfacción es señal de conformismo.',
    'Disfrutar el camino también es respetar el proceso.',
    'No tienes que tener más para empezar a disfrutar más.',
    'Lo que celebras hoy te da energía para lo que construyes mañana.',
    'No toda alegría hay que ganarla. Algunas ya la tienes.',
    'Disfrutar sin culpa también es crecimiento.',
    'No tienes que sacrificar el presente en nombre del futuro.',
    'Lo que disfrutas en el proceso también es aprendizaje.',
    'No toda satisfacción viene del logro. Algunas vienen del ser.',
    'Disfrutar también es una señal de que estás en el lugar correcto.',
    'No tienes que esperar al resultado para disfrutar del trabajo.',
    'Lo que tienes hoy es también el fruto de decisiones pasadas.',
    'No toda pausa para disfrutar frena el crecimiento.',
    'Disfrutar de lo que has construido es también motivación.',
    'No tienes que estar siempre en tensión para crecer.',
    'Lo que celebras también refuerza lo que quieres repetir.',
    'No toda ambición necesita ir acompañada de insatisfacción.',
    'Disfrutar el presente también es confiar en el futuro.',
    'No tienes que llegar a ningún lado especial para estar bien ahora.',
    'Lo que disfrutas hoy también es lo que recuerdas mañana.',
    'No toda alegría necesita justificación.',
    'Disfrutar también requiere atención. No se da solo.',
    'No tienes que posponer la vida en nombre del crecimiento.',
    'Lo que ya eres ya vale. Lo que serás también.',
    'No toda satisfacción es señal de que ya terminaste.',
    'Disfrutar también es estrategia.',
    'No tienes que ser otra persona para disfrutar más.',
    'Lo que celebras hoy también define quién eres.',
    'No toda alegría viene del logro. Algunas vienen del camino.',
    'Disfrutar también es parte del crecimiento.',
    'No tienes que esperar a merecer el disfrute. Ya lo mereces.',
    'Lo que tienes ahora también es suficiente para estar bien.',
  ],
  'conexion-construyendo': [
    'Lo que construyes con otros tiene más peso que lo que construyes solo.',
    'Las mejores ideas no viven en una sola cabeza.',
    'Construir relaciones también es estrategia.',
    'Lo que haces resuena en quienes te rodean. Úsalo bien.',
    'La colaboración no es debilidad. Es multiplicación.',
    'No todo se construye mejor solo.',
    'Las personas correctas aceleran lo que construyes.',
    'No toda ayuda recibida te hace menos.',
    'Construir con otros también te construye a ti.',
    'No todo lo que construyes tiene que ser tuyo solo para ser valioso.',
    'Las relaciones también son infraestructura.',
    'No tienes que hacerlo todo tú para que sea tuyo.',
    'Construir con las personas correctas cambia el resultado.',
    'No toda colaboración es perder control. Algunas es ganar potencia.',
    'Las conversaciones correctas también construyen.',
    'No tienes que ir solo para llegar lejos.',
    'Construir con otros requiere también saber ceder.',
    'No toda diferencia de opinión frena. Algunas mejoran lo que construyes.',
    'Las personas que suman también hay que cuidarlas.',
    'No todo lo que se construye en equipo es más lento.',
    'Construir relaciones sólidas es también construir futuro.',
    'No tienes que tener todo el conocimiento si tienes las personas correctas.',
    'Las conexiones correctas abren puertas que el esfuerzo solo no puede.',
    'No toda vulnerabilidad al construir con otros es riesgo.',
    'Construir con confianza es construir más rápido.',
    'No tienes que demostrarte a ti mismo haciendo todo solo.',
    'Las mejores cosas que se construyen tienen más de una mente detrás.',
    'No toda dependencia en otros es debilidad.',
    'Construir con personas que te desafían es construir mejor.',
    'No tienes que proteger cada idea. Compartir también construye.',
    'Las relaciones también se construyen. No aparecen solas.',
    'No todo lo que construyes en solitario tiene la profundidad de lo construido en comunidad.',
    'Construir también es saber a quién llamar.',
    'No tienes que tener todo resuelto antes de involucrar a otros.',
    'Las personas que creen en lo que construyes también lo hacen crecer.',
    'No toda crítica de quien te rodea hay que ignorarla.',
    'Construir en comunidad genera más que construir en aislamiento.',
    'No tienes que ser el único con la visión para que la visión avance.',
    'Las conexiones que cuidas también te cuidan.',
    'No todo lo que construyes necesita audiencia. Pero algunas cosas sí.',
    'Construir con otros también te enseña sobre ti.',
    'No tienes que hacer todo para merecer lo que construyes.',
    'Las personas correctas a tu lado cambian lo que es posible.',
    'No toda colaboración es igual. Elige bien con quién construyes.',
    'Construir relaciones también requiere inversión constante.',
    'No tienes que ir más rápido que los demás. Tienes que ir en la dirección correcta.',
    'Las conexiones que nutres también nutren lo que construyes.',
    'No toda soledad en el proceso es señal de que algo va mal.',
    'Construir con personas que complementan lo que no tienes es inteligencia.',
    'No tienes que hacerlo perfecto para que quienes construyen contigo lo valoren.',
  ],
  'conexion-sanando': [
    'Dejarte ayudar también es un acto de valentía.',
    'No tienes que sanar en silencio.',
    'Las personas correctas no te juzgan por tus grietas.',
    'Compartir lo que pesa no es carga. Es confianza.',
    'La conexión real cura lo que el tiempo solo no puede.',
    'No toda vulnerabilidad es debilidad. Algunas son puentes.',
    'Sanar con apoyo es más rápido y más profundo.',
    'No tienes que proteger a todos de lo que sientes.',
    'Las personas que se quedan cuando estás mal son las que importan.',
    'No toda soledad en el proceso de sanar es necesaria.',
    'Dejarte ver también es sanar.',
    'No tienes que tener todo resuelto antes de conectar.',
    'Las conversaciones honestas también sanan.',
    'No toda conexión es igual. Las correctas suman.',
    'Sanar también es aprender a recibir.',
    'No tienes que demostrar que estás bien para ser querido.',
    'Las relaciones que te permiten ser quien eres también sanan.',
    'No toda ayuda hay que pagarla de inmediato.',
    'Sanar con otros cambia la calidad del proceso.',
    'No tienes que ser fuerte delante de todos.',
    'Las conexiones que cuidas también te cuidan cuando lo necesitas.',
    'No toda apertura es riesgo. Algunas son liberación.',
    'Sanar también requiere dejarse querer.',
    'No tienes que cargar solo con todo para ser válido.',
    'Las personas que te ven en el proceso también forman parte de la sanación.',
    'No toda conexión tiene que ser perfecta para ser valiosa.',
    'Sanar con la mirada de alguien que cree en ti acelera el proceso.',
    'No tienes que estar bien para conectar. Puedes conectar mientras sanas.',
    'Las relaciones que sobreviven a los momentos difíciles son las reales.',
    'No toda soledad es elegida. Pero algunas sí se pueden cambiar.',
    'Sanar también es aprender qué personas te hacen bien.',
    'No tienes que justificar tu necesidad de apoyo.',
    'Las conversaciones que curan también son actos de amor.',
    'No toda conexión que buscas cuando estás mal es dependencia.',
    'Sanar también es confiar en que hay personas que quieren ayudarte.',
    'No tienes que haber perdido mucho para merecer apoyo.',
    'Las relaciones sanas también se construyen desde la vulnerabilidad.',
    'No toda apertura implica riesgo. Algunas implican alivio.',
    'Sanar en comunidad es más sostenible que sanar en solitario.',
    'No tienes que esperar a estar bien para conectar con quien te cuida.',
    'Las personas que te ven sanar también crecen contigo.',
    'No toda dependencia emocional es mala. Algunas son necesarias.',
    'Sanar también es redescubrir que no estás solo.',
    'No tienes que resolver todo antes de pedir ayuda.',
    'Las conexiones que nutres en momentos buenos también están cuando los necesitas.',
    'No toda apertura tiene que ser total. Puedes elegir cuánto compartir.',
    'Sanar también es aprender a confiar de nuevo.',
    'No tienes que cargar con todo para demostrar que puedes.',
    'Las personas correctas a tu lado hacen que el proceso duela menos.',
    'No toda conexión que buscas en momentos difíciles es debilidad.',
  ],
  'conexion-buscando': [
    'A veces lo que buscas ya está en una conversación que aún no tuviste.',
    'Las personas que aparecen no siempre son casualidad.',
    'Buscar junto a otros es más rico que buscar en soledad.',
    'El otro a veces ve en ti lo que tú aún no ves.',
    'Preguntar también es una forma de conectar.',
    'No toda búsqueda necesita ser solitaria.',
    'Las personas correctas también te ayudan a encontrar lo que buscas.',
    'No tienes que saber exactamente qué buscas para conectar.',
    'Buscar con otros multiplica las perspectivas.',
    'No toda conexión que buscas es romántica. Algunas son las más importantes.',
    'Las conversaciones correctas también revelan lo que buscas.',
    'No tienes que encontrar solo para que el hallazgo sea tuyo.',
    'Buscar también es estar abierto a lo que llega.',
    'No toda conexión hay que forzarla. Las correctas llegan.',
    'Las personas con las que conectas también definen lo que encuentras.',
    'No tienes que buscar en soledad lo que otros también están buscando.',
    'Buscar conexión también es buscar crecimiento.',
    'No toda búsqueda tiene que ser interior.',
    'Las relaciones que buscas también te están buscando.',
    'No tienes que tener todo resuelto para conectar.',
    'Buscar con apertura genera más que buscar con esquemas rígidos.',
    'No toda conexión que te mueve es la que esperabas.',
    'Las personas que aparecen en tu búsqueda también son parte del hallazgo.',
    'No tienes que saber exactamente qué buscas para reconocerlo cuando llegue.',
    'Buscar también requiere estar dispuesto a ser encontrado.',
    'No toda búsqueda de conexión necesita estrategia.',
    'Las conversaciones inesperadas también revelan lo que buscas.',
    'No tienes que buscar lejos lo que puede estar cerca.',
    'Buscar con los demás también te muestra quién eres.',
    'No toda conexión que buscas tiene que durar para ser valiosa.',
    'Las personas correctas también aparecen cuando estás en movimiento.',
    'No tienes que estar solo en la búsqueda.',
    'Buscar con apertura a las personas también es buscar con inteligencia.',
    'No toda conexión se encuentra. Algunas se construyen.',
    'Las relaciones que buscas también se alimentan de lo que das.',
    'No tienes que saber exactamente qué tipo de conexión buscas.',
    'Buscar también es estar presente en los lugares correctos.',
    'No toda búsqueda de conexión es necesidad. Algunas son sabiduría.',
    'Las personas que te encuentran cuando buscas también tienen algo que enseñarte.',
    'No tienes que buscar solo para encontrar algo que sea tuyo.',
    'Buscar conexión también es declarar que crees en los demás.',
    'No toda conexión que buscas llega en el momento que esperas.',
    'Las conversaciones que buscas también te cambian.',
    'No tienes que tener algo que ofrecer para buscar conexión.',
    'Buscar también implica estar dispuesto a que te sorprendan.',
    'No toda búsqueda de conexión termina en lo que esperabas. A veces termina mejor.',
    'Las personas que aparecen cuando buscas no siempre son las que buscabas.',
    'No tienes que saber adónde vas para conectar con quien va en tu dirección.',
    'Buscar también es una forma de confiar en que hay algo que encontrar.',
    'No toda conexión que buscas está en los lugares que conoces.',
  ],
  'conexion-disfrutando': [
    'Los momentos con las personas correctas no se recuperan. Están ahora.',
    'La presencia es el regalo más escaso que puedes dar.',
    'Estar aquí, con quien importa, ya es suficiente.',
    'La alegría compartida no se divide. Se multiplica.',
    'Hoy, solo por esto, ya fue un buen día.',
    'No toda felicidad es solitaria. Las mejores suelen ser compartidas.',
    'Las personas que te hacen bien también merecen tu presencia real.',
    'No tienes que hacer nada especial para disfrutar con quien quieres.',
    'Los momentos ordinarios con personas extraordinarias son los que más recuerdas.',
    'No toda celebración necesita ser grande.',
    'Disfrutar con otros también es un acto de generosidad.',
    'No tienes que estar en ningún lado especial para estar bien con quien quieres.',
    'Las risas compartidas también son infraestructura de las relaciones.',
    'No toda conexión que disfrutas necesita propósito.',
    'Disfrutar de las personas que tienes también es gratitud.',
    'No tienes que esperar a una ocasión especial para estar presente.',
    'Los momentos con quienes quieres también te definen.',
    'No toda alegría compartida necesita ser celebrada en voz alta.',
    'Disfrutar con otros también te recuerda quién eres.',
    'No tienes que planificar los mejores momentos. Algunos solo pasan.',
    'Las personas que te alegran también merecen saber que lo hacen.',
    'No toda conexión que disfrutas necesita análisis.',
    'Disfrutar de las personas que tienes es también cuidarlas.',
    'No tienes que esperar a tener tiempo para estar presente.',
    'Los momentos de conexión real también recargan.',
    'No toda alegría compartida es casual. Algunas se construyen.',
    'Disfrutar con quien quieres también es una elección.',
    'No tienes que tener todo resuelto para disfrutar de quien tienes.',
    'Las conversaciones que te hacen bien también son combustible.',
    'No toda conexión que disfrutas tiene que durar para importar.',
    'Disfrutar del presente con quien importa es también futuro.',
    'No tienes que ir a ningún lado especial para tener los mejores momentos.',
    'Las personas con las que ríes también te cuidan sin que lo notes.',
    'No toda alegría compartida necesita ser recordada para haber valido.',
    'Disfrutar de lo que tienes, con quien tienes, es suficiente.',
    'No tienes que esperar a que todo esté bien para estar bien con quien quieres.',
    'Los momentos de conexión real compensan muchos momentos difíciles.',
    'No toda celebración necesita motivo externo.',
    'Disfrutar con otros también te recuerda que no estás solo.',
    'No tienes que tener todo bajo control para disfrutar de quien tienes.',
    'Las personas que disfrutas también merecen tu atención real.',
    'No toda conexión que valoras hay que decirla en voz alta. Pero a veces sí.',
    'Disfrutar también es estar disponible para quienes quieres.',
    'No tienes que ganarte los momentos de alegría compartida.',
    'Las conexiones que cuidas también son las que más disfrutas.',
    'No toda alegría con otros necesita ser perfecta para ser real.',
    'Disfrutar de las personas que tienes también es invertir en ti.',
    'No tienes que tener mucho para disfrutar mucho con quien quieres.',
    'Los momentos sencillos con personas reales son los más valiosos.',
    'No toda conexión que disfrutas necesita futuro para tener valor hoy.',
  ],
  'proposito-construyendo': [
    'Lo que haces tiene sentido aunque todavía no veas el cuadro completo.',
    'Construir con propósito es diferente a construir con prisa.',
    'Cada acción pequeña con intención suma más de lo que parece.',
    'El propósito no se encuentra. Se construye, decisión a decisión.',
    'Lo que estás levantando va más allá de ti. Eso importa.',
    'No todo lo que construyes con propósito tiene éxito inmediato.',
    'El por qué detrás de lo que construyes también es parte del resultado.',
    'No tienes que ver el final para saber que vale la pena construir.',
    'Construir con sentido también atrae a las personas correctas.',
    'No toda acción con propósito necesita ser grande para importar.',
    'El propósito claro también actúa como filtro de lo que no merece tu energía.',
    'No tienes que explicarle a todos por qué construyes lo que construyes.',
    'Construir algo con sentido también te sostiene cuando es difícil.',
    'No toda dificultad en lo que construyes significa que vas mal.',
    'El propósito también se prueba en los momentos difíciles.',
    'No tienes que tener el propósito completamente definido para empezar.',
    'Construir desde el para qué es más sostenible que construir desde el qué.',
    'No toda construcción con propósito necesita audiencia para tener valor.',
    'El sentido de lo que haces también afecta cómo lo haces.',
    'No tienes que convencer a todos de tu propósito para que sea válido.',
    'Construir con intención también genera más energía que construir por inercia.',
    'No toda claridad de propósito llega antes de empezar. Algunas llega mientras.',
    'El propósito también se refina con el tiempo y la experiencia.',
    'No tienes que tener certeza total sobre tu propósito para actuar.',
    'Construir también es descubrir para qué sirve lo que estás construyendo.',
    'No toda duda sobre el propósito es señal de que está equivocado.',
    'El sentido que le das a lo que construyes también lo hace más sólido.',
    'No tienes que tener el propósito perfecto para empezar a construir.',
    'Construir con propósito también requiere revisar si el propósito sigue siendo tuyo.',
    'No toda construcción con sentido es visible para los demás.',
    'El propósito también se construye haciendo.',
    'No tienes que esperar a tener todo el propósito claro para construir.',
    'Construir desde el sentido también genera más resistencia ante los obstáculos.',
    'No toda dificultad en el camino de lo que construyes invalida el propósito.',
    'El propósito también cambia. Y está bien.',
    'No tienes que tener el mismo propósito para siempre.',
    'Construir con sentido también es construir con identidad.',
    'No toda acción con propósito tiene que ser perfecta.',
    'El para qué de lo que construyes también es parte de la estrategia.',
    'No tienes que justificar tu propósito ante nadie.',
    'Construir también es descubrir qué te importa realmente.',
    'No toda construcción tiene sentido desde el inicio. Algunas lo van encontrando.',
    'El propósito sostenido también requiere revisiones periódicas.',
    'No tienes que tener el propósito más grande del mundo para que valga.',
    'Construir con sentido también requiere coraje para no desviarte.',
    'No toda claridad de propósito es permanente. Se trabaja.',
    'El sentido de lo que construyes también define cómo lo construyes.',
    'No tienes que tener todo claro para saber que lo que haces importa.',
    'Construir con propósito es también construir con honestidad.',
    'No todo lo que construyes tiene que tener impacto masivo para tener sentido.',
  ],
  'proposito-sanando': [
    'Lo que viviste no fue en vano si lo conviertes en dirección.',
    'Sanar también es descubrir qué es lo que realmente importa.',
    'Tu historia, con todo lo que tiene, es única. Úsala.',
    'Del dolor también nace la claridad sobre lo esencial.',
    'Volver a ti es el primer paso hacia cualquier propósito real.',
    'No tienes que haber tenido todo claro antes para encontrar propósito ahora.',
    'Sanar también revela para qué estás aquí.',
    'No toda herida bloquea el propósito. Algunas lo definen.',
    'Lo que superaste también es parte de tu capacidad única.',
    'No tienes que haber tenido un camino fácil para tener un propósito poderoso.',
    'Sanar también es recuperar la conexión con lo que te importa.',
    'No toda pérdida te aleja del propósito. Algunas te acercan.',
    'Lo que viviste también amplió tu capacidad de ayudar a otros.',
    'No tienes que estar completamente bien para empezar a vivir con propósito.',
    'Sanar también es recuperar la energía para lo que importa.',
    'No toda dificultad pasada es un obstáculo para el propósito futuro.',
    'Lo que te costó llegar hasta aquí también es parte de tu propósito.',
    'No tienes que tener todo sanado para empezar a construir sentido.',
    'Sanar también es descubrir que tienes algo que ofrecer.',
    'No toda herida bloquea. Algunas son el origen de tu mayor contribución.',
    'Lo que viviste también te dio perspectiva que otros no tienen.',
    'No tienes que haber superado todo para empezar a vivir con intención.',
    'Sanar también es encontrar el para qué de lo que pasó.',
    'No toda experiencia difícil carece de sentido.',
    'Lo que has superado también es evidencia de tu capacidad.',
    'No tienes que esperar a estar bien del todo para empezar a vivir con propósito.',
    'Sanar también es recuperar la confianza en lo que puedes hacer.',
    'No toda herida necesita explicación para generar propósito.',
    'Lo que viviste también es parte de lo que te hace único.',
    'No tienes que haber tenido un origen fácil para tener un destino significativo.',
    'Sanar también es redescubrir qué te mueve.',
    'No toda dificultad pasada te define negativamente.',
    'Lo que superaste también es la base de lo que puedes construir.',
    'No tienes que convertir todo el dolor en propósito. Pero puedes elegir.',
    'Sanar también es recuperar el sentido de lo cotidiano.',
    'No toda herida necesita ser transformada para poder seguir.',
    'Lo que viviste también te dio herramientas que otros no tienen.',
    'No tienes que esperar a entender todo lo que pasó para avanzar.',
    'Sanar también es reconectar con lo que quieres construir.',
    'No toda experiencia difícil bloquea el propósito. Algunas lo clarifican.',
    'Lo que has pasado también ha construido quién eres hoy.',
    'No tienes que haber tenido todo fácil para tener un propósito claro.',
    'Sanar también es recuperar la capacidad de imaginar lo que viene.',
    'No toda herida necesita ser el centro de tu historia.',
    'Lo que viviste también puede ser la razón por la que algo que haces importa.',
    'No tienes que haber superado todo para empezar a construir algo con sentido.',
    'Sanar también es descubrir que el dolor también puede tener dirección.',
    'No toda experiencia difícil necesita justificación para tener valor.',
    'Lo que has superado también es evidencia de que puedes superar lo que viene.',
    'No tienes que convertir tu historia en narrativa pública para encontrar propósito en ella.',
  ],
  'proposito-buscando': [
    'El propósito no siempre llega claro. A veces es solo una dirección.',
    'Buscar sentido ya es vivir con más profundidad que la mayoría.',
    'No tengas prisa. Las respuestas importantes no se apuran.',
    'La pregunta más importante no es adónde vas, sino por qué.',
    'Estás más cerca de lo que crees. Presta atención.',
    'No toda búsqueda de propósito termina en revelación. A veces termina en claridad gradual.',
    'Buscar el para qué también es honrarte.',
    'No tienes que encontrar el propósito de golpe.',
    'La búsqueda de sentido también te cambia mientras buscas.',
    'No toda incertidumbre sobre el propósito es vacío. Algunas es espacio.',
    'Buscar el propósito con honestidad es ya una forma de vivir con intención.',
    'No tienes que tener el propósito más grande para que tu búsqueda sea válida.',
    'La búsqueda de sentido también te muestra qué no es para ti.',
    'No toda pregunta sobre el propósito tiene respuesta rápida.',
    'Buscar el para qué también requiere escucharte.',
    'No tienes que saber exactamente qué buscas para saber que vale la pena buscarlo.',
    'La búsqueda de propósito también es una búsqueda de ti.',
    'No toda claridad de propósito llega antes de actuar. Algunas llega actuando.',
    'Buscar el sentido también requiere tolerar la incertidumbre.',
    'No tienes que justificar tu búsqueda de propósito.',
    'La búsqueda honesta de sentido también genera respeto propio.',
    'No toda búsqueda de propósito necesita testigos.',
    'Buscar el para qué también es lo que diferencia una vida elegida de una vivida por inercia.',
    'No tienes que tener todo claro para empezar a buscar con intención.',
    'La búsqueda de sentido también requiere soltar lo que no es tuyo.',
    'No toda duda sobre el propósito es señal de que vas mal.',
    'Buscar el para qué también implica revisar qué ya no tiene sentido.',
    'No tienes que saber el destino para saber qué dirección tiene más sentido.',
    'La búsqueda de propósito también te enseña sobre lo que valoras.',
    'No toda búsqueda de sentido es existencial. Algunas son cotidianas.',
    'Buscar también es descartar. Y descartar también es avanzar.',
    'No tienes que tener el propósito definitivo para vivir con más intención hoy.',
    'La búsqueda de sentido también requiere honestidad sobre qué te mueve realmente.',
    'No toda claridad de propósito es permanente. Evoluciona.',
    'Buscar el para qué también requiere paciencia con uno mismo.',
    'No tienes que encontrar el propósito de vida para vivir con propósito hoy.',
    'La búsqueda de sentido también es una forma de respetarte.',
    'No toda búsqueda de propósito es solitaria.',
    'Buscar el para qué también requiere estar dispuesto a cambiar.',
    'No tienes que tener todo bajo control para buscar propósito.',
    'La búsqueda de sentido también genera energía cuando la encuentras.',
    'No toda búsqueda de propósito necesita ser dramática.',
    'Buscar el para qué también te ayuda a tomar mejores decisiones.',
    'No tienes que haber perdido el propósito para buscarlo.',
    'La búsqueda de sentido también te hace más claro en lo que priorizas.',
    'No toda búsqueda de propósito termina donde esperabas.',
    'Buscar el para qué también requiere soltar lo que ya no encaja.',
    'No tienes que tener el propósito perfecto para empezar a actuar con sentido.',
    'La búsqueda de propósito también es una declaración de que te importas.',
    'No toda búsqueda de sentido necesita un final claro para tener valor.',
  ],
  'proposito-disfrutando': [
    'Vivir bien también es un propósito. No lo subestimes.',
    'El sentido a veces está en lo ordinario, no en lo extraordinario.',
    'Hacer bien las cosas pequeñas también cuenta.',
    'Tener claro lo que valoras y vivir acorde a ello. Eso es propósito.',
    'Hoy tienes todo lo que necesitas para vivir con intención.',
    'No toda vida con propósito es dramática. Algunas son tranquilas y plenas.',
    'Disfrutar de lo que tienes con intención también es propósito.',
    'No tienes que buscar el gran propósito si ya vives con sentido.',
    'El propósito también puede ser disfrutar plenamente lo que ya tienes.',
    'No toda vida con propósito requiere sacrificio constante.',
    'Disfrutar con consciencia también es vivir con propósito.',
    'No tienes que tener el propósito más visible para que sea real.',
    'El sentido también se encuentra en lo cotidiano bien vivido.',
    'No toda vida con sentido necesita ser contada.',
    'Disfrutar de lo que construiste también es parte del propósito.',
    'No tienes que buscar más propósito si ya estás viviendo con el tuyo.',
    'El propósito también puede ser vivir bien y con plenitud.',
    'No toda vida con propósito necesita impacto masivo.',
    'Disfrutar del presente con intención también es vivir con propósito.',
    'No tienes que estar siempre construyendo para vivir con sentido.',
    'El propósito también se expresa en cómo disfrutas lo que tienes.',
    'No toda vida con propósito es visible desde fuera.',
    'Disfrutar de lo que eres y de lo que tienes también es intencional.',
    'No tienes que justificar que tu propósito sea vivir bien.',
    'El sentido también puede estar en la calidad de lo cotidiano.',
    'No toda vida con propósito necesita urgencia.',
    'Disfrutar con consciencia también genera sentido.',
    'No tienes que tener el propósito más grande para vivir con intención.',
    'El propósito también puede ser simple y profundo a la vez.',
    'No toda vida con sentido requiere ruido externo.',
    'Disfrutar plenamente también es una forma de agradecer.',
    'No tienes que estar siempre en modo misión para vivir con propósito.',
    'El sentido también vive en los momentos que decides valorar.',
    'No toda vida con propósito necesita validación.',
    'Disfrutar de lo que has construido también tiene sentido.',
    'No tienes que tener un propósito distinto al de vivir bien y plenamente.',
    'El propósito también se expresa en la calidad de tu presencia.',
    'No toda vida con sentido necesita ser complicada.',
    'Disfrutar también es un acto de propósito cuando es consciente.',
    'No tienes que buscar el gran sentido si el pequeño ya te llena.',
    'El propósito también puede ser estar bien y hacer que otros estén bien.',
    'No toda vida con propósito necesita cambiar el mundo.',
    'Disfrutar de lo que tienes con plena consciencia también es propósito.',
    'No tienes que esperar a encontrar el gran propósito para vivir con intención.',
    'El sentido también está en elegir disfrutar lo que ya tienes.',
    'No toda vida con propósito necesita ser difícil.',
    'Disfrutar plenamente también es una forma de vivir con intención.',
    'No tienes que tener el propósito más ambicioso para que sea válido.',
    'El propósito también puede ser crear momentos de alegría y conexión.',
    'No toda vida con sentido es heroica. Algunas son simplemente plenas.',
  ],
  'default': [
    'Tienes más claridad de la que crees. Solo necesitas parar un segundo.',
    'La siguiente decisión no tiene que ser perfecta. Solo tiene que ser tuya.',
    'Foco. No en todo. En lo que importa.',
    'Haz menos cosas, pero hazlas de verdad.',
    'La dirección importa más que la velocidad.',
    'No toda acción suma. Elige cuáles importan.',
    'El ruido no es señal de progreso.',
    'Parar a pensar también es avanzar.',
    'No tienes que tener todo claro para empezar.',
    'Lo que haces con constancia supera a lo que haces con intensidad.',
    'No toda urgencia es real.',
    'El foco es escaso. Úsalo bien.',
    'No tienes que responder a todo.',
    'Lo importante raramente grita. Suele susurrar.',
    'No toda opinión merece tu energía.',
    'El progreso lento también es progreso.',
    'No tienes que justificar cada decisión.',
    'Lo que no haces también define quién eres.',
    'No toda información es útil. Filtra.',
    'El tiempo que dedicas a lo que importa también se nota.',
  ],
}
